---
- name: "Update FPM pool configurations"
  template:
      src: "php-fpm.conf.j2"
      dest: "/etc/php-fpm.d/{{ item['pool_name'] }}.conf"
      owner: root
      group: root
  with_items:
  - "{{ php_php_fpm_pools }}"

- name: "Enable PHP-FPM to start on boot"
  service:
    name: "{{ _php_fpm_daemon[ansible_os_family] }}"
    state: started
    enabled: yes
